### ISSUE TITLE
Include support for Frappe on Windows 10 WSL

### ISSUE THREAD

**Issue by davidjeba** [frappe/frappejs#129]
https://docs.microsoft.com/en-us/windows/wsl/install-win10

Please include support for frappe on Windows via WSL

**Comment by bondmojo** [comment]
i was able to build frappejs on windows 10. It requires python 2.7 to build this

**Comment by satyajitghana** [comment]
@bondmojo I have python2 as well as python3, but still it fails to build

```
../src/bcrypt_node.cc:65:6: warning: ‘char {anonymous}::ToCharVersion(v8::Local<v8::String>)’ defined but not used [-Wunused-function]
   65 | char ToCharVersion(Local<String> str) {
      |      ^~~~~~~~~~~~~
make: *** [bcrypt_lib.target.mk:113: Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
make: Leaving directory '/home/shadowleaf/ink-work/frappe-react/node_modules/frappejs/node_modules/bcrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/shadowleaf/ink-work/frappe-react/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 4.19.128-microsoft-standard
gyp ERR! command "/usr/local/bin/node" "/home/shadowleaf/ink-work/frappe-react/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/shadowleaf/ink-work/frappe-react/node_modules/frappejs/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/home/shadowleaf/ink-work/frappe-react/node_modules/frappejs/node_modules/bcrypt/lib/binding" "--napi_version=8" "--node_abi_napi=napi"
gyp ERR! cwd /home/shadowleaf/ink-work/frappe-react/node_modules/frappejs/node_modules/bcrypt
gyp ERR! node -v v14.17.6
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /home/shadowleaf/ink-work/frappe-react/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/shadowleaf/ink-work/frappe-react/node_modules/frappejs/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/home/shadowleaf/ink-work/frappe-react/node_modules/frappejs/node_modules/bcrypt/lib/binding --napi_version=8 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/shadowleaf/ink-work/frappe-react/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Linux 4.19.128-microsoft-standard
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/shadowleaf/ink-work/frappe-react/node_modules/frappejs/node_modules/bcrypt/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/shadowleaf/ink-work/frappe-react/node_modules/frappejs/node_modules/bcrypt
node-pre-gyp ERR! node -v v14.17.6
node-pre-gyp ERR! node-pre-gyp -v v0.9.1
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /home/shadowleaf/ink-work/frappe-react/node_modules/node-gyp/bin/node-gyp.js 
```
