### ISSUE TITLE
Unable to install frappejs

### ISSUE THREAD

**Issue by jcbolor** [frappe/frappejs#132]
After running `yarn add frappejs`

**I got this error:**
make: *** [bcrypt_lib.target.mk:113: Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
make: Leaving directory '/home/jc/Desktop/frappejs/node_modules/bcrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/jc/Desktop/frappejs/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (node:events:369:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Linux 5.8.0-48-generic
gyp ERR! command "/usr/bin/node" "/home/jc/Desktop/frappejs/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/jc/Desktop/frappejs/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/home/jc/Desktop/frappejs/node_modules/bcrypt/lib/binding" "--napi_version=8" "--node_abi_napi=napi"
gyp ERR! cwd /home/jc/Desktop/frappejs/node_modules/bcrypt
gyp ERR! node -v v15.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /home/jc/Desktop/frappejs/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/jc/Desktop/frappejs/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/home/jc/Desktop/frappejs/node_modules/bcrypt/lib/binding --napi_version=8 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/jc/Desktop/frappejs/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:369:20)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
node-pre-gyp ERR! System Linux 5.8.0-48-generic
node-pre-gyp ERR! command "/usr/bin/node" "/home/jc/Desktop/frappejs/node_modules/bcrypt/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/jc/Desktop/frappejs/node_modules/bcrypt
node-pre-gyp ERR! node -v v15.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.9.1
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /home/jc/Desktop/frappejs/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/jc/Desktop/frappejs/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_

**Comment by mingfang** [comment]
same problem when I tried to install on Ubuntu 20.04.
How can such an obvious problem still not fixed?

**Comment by bondmojo** [comment]
@rmehta can anyone help here?

**Comment by saru2020** [comment]
Did anyone get beyond this?
Or is this project dead?
