### ISSUE TITLE
Non fatal error. Everything working but honcho start terminal shows this error

### ISSUE THREAD

**Issue by revant** [frappe/frappejs#23]
```
revant@revant-laptop:~/frappe-js/frappe-todo$ nf start
[WARN] No ENV file found
16:06:50 server.1   |  [nodemon] 1.14.11
16:06:50 server.1   |  [nodemon] to restart at any time, enter `rs`
16:06:50 server.1   |  [nodemon] watching: *.*
16:06:50 server.1   |  [nodemon] starting `node server.js`
16:06:52 watch.1    |  rollup v0.55.1
16:06:52 watch.1    |  bundles ./node_modules/frappejs/client/style/index.scss → dist/css/style.css...
16:06:52 watch.1    |  created dist/css/style.css in 677ms
16:06:52 watch.1    |  bundles ./src/index.js → dist/js/bundle.js...
16:06:53 server.1   |  [nodemon] restarting due to changes...
16:06:53 watch.1    |  created dist/js/bundle.js in 724ms
16:06:53 server.1   |  [nodemon] restarting due to changes...
16:06:53 server.1   |  [nodemon] starting `node server.js`
16:06:53 server.1   |  events.js:183
16:06:53 server.1   |        throw er; // Unhandled 'error' event
16:06:53 server.1   |        ^
16:06:53 server.1   |  Error: listen EADDRINUSE :::8000
16:06:53 server.1   |      at Object._errnoException (util.js:1022:11)
16:06:53 server.1   |      at _exceptionWithHostPort (util.js:1044:20)
16:06:53 server.1   |      at Server.setupListenHandle [as _listen2] (net.js:1351:14)
16:06:53 server.1   |      at listenInCluster (net.js:1392:12)
16:06:53 server.1   |      at Server.listen (net.js:1476:7)
16:06:53 server.1   |      at Function.listen (/home/revant/frappe-js/frappejs/node_modules/express/lib/application.js:618:24)
16:06:53 server.1   |      at Object.start (/home/revant/frappe-js/frappejs/server/index.js:32:29)
16:06:53 server.1   |      at <anonymous>
16:06:53 server.1   |  [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by revant** [comment]
```
killall -9 node
```
solved it
https://stackoverflow.com/a/16107404
