### ISSUE TITLE
async >start< SyntaxError: Unexpected identifier, nodejs v6.12.3

### ISSUE THREAD

**Issue by revant** [frappe/frappejs#24]
Error starting todo app
```
 /home/dell/frappe-js/frappejs/server/index.js:14
    async start({backend, connection_params, static, models_path}) {
          ^^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/dell/frappe-js/frappe-todo/server.js:1:78)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by revant** [comment]
works on stable or latest nodejs

for ubuntu users - https://askubuntu.com/a/480642
